apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: eshop
  labels:
    app: apig
  name: apig
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: apig
  type: NodePort
status:
  loadBalancer: {}
